name: "CI Build & Publish"

on:
  push:
    branches:
      - main

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.2
          cache: 'npm'

      - name: Install npm packages
        run: npm install

      - name: Build
        run: npm run build

      - uses: actions/upload-artifact@v3
        with:
          name: engine
          path: ./dist/

      - name: Publish NPM package
        run: npm publish
        env:
          TOKEN: ${{ secrets.TOKEN }}